// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Ecx7eNODzWux2HfGrH25rrbe5wWkqIE',
    appId: '1:903243239110:web:e144f63eedeff456ba11c7',
    messagingSenderId: '903243239110',
    projectId: 'dine-delish-app',
    authDomain: 'dine-delish-app.firebaseapp.com',
    storageBucket: 'dine-delish-app.appspot.com',
    measurementId: 'G-MP21FGRXFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSHiPgl70InAtuMPY0RN669GpvCzyk2f8',
    appId: '1:903243239110:android:21cf0da0aec97888ba11c7',
    messagingSenderId: '903243239110',
    projectId: 'dine-delish-app',
    storageBucket: 'dine-delish-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI4huxRIIBo_fb46Krwb2WcuAIOC8zUSM',
    appId: '1:903243239110:ios:190dcf3aeccc81edba11c7',
    messagingSenderId: '903243239110',
    projectId: 'dine-delish-app',
    storageBucket: 'dine-delish-app.appspot.com',
    iosClientId: '903243239110-vn73n1blif8tv5thkb3ti6b97rkd1e9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI4huxRIIBo_fb46Krwb2WcuAIOC8zUSM',
    appId: '1:903243239110:ios:190dcf3aeccc81edba11c7',
    messagingSenderId: '903243239110',
    projectId: 'dine-delish-app',
    storageBucket: 'dine-delish-app.appspot.com',
    iosClientId: '903243239110-vn73n1blif8tv5thkb3ti6b97rkd1e9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );
}
