name: settingpage
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Define the version and build number for your application.
version: 1.0.0+1

# Specify the minimum Flutter SDK version.
environment:
  sdk: '>=3.0.5 <4.0.0'

# Define your package dependencies.
dependencies:
  flutter:
    sdk: flutter

  # Add the Cupertino Icons font for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter

# Define development dependencies (for testing).
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Use the "flutter_lints" package for recommended code linting rules.
  flutter_lints: ^2.0.0

# Configure Flutter-specific settings.
flutter:
  # Ensure that the Material Icons font is included with your application.
  uses-material-design: true

  # Specify the assets used in your application.
  assets:
    - assets/restaurant1.png
    - assets/restaurant2.png
    - assets/restaurant3.png
    - assets/restaurant4.png

  # You can also add custom fonts if needed.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
